#cloud-config
repo_upgrade: security
write_files:
- path: "/tmp/bootstrap-userdata"
  encoding: b64
  permissions: 0500
  content: "${LaunchScript}"
runcmd:
- [ "/tmp/bootstrap-userdata", "${ApiEndpoint}" ]